name: e2e testing

on:
  push:
    branches:
      - e2e

jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          repository: rht-labs/lodestar-frontend
      - name: e2e run
        uses: cypress-io/github-action@v2
        with:
          browser: chrome